Landing Page Products list
CraftAcademy/slowfood-june-2019_team-2 pull request #3
Opened 2019-10-01 07:58 UTC by AlexSaxena

# Adding Product List feature
[PT-Link](https://www.pivotaltracker.com/story/show/168829452)

## PR Content
In this PR we are creating a products list for our landing page.

Includes feature and tests in step definitions.

## What we have learned 
Deeper understanding of the AUT-cycle

![IMG_7396](https://user-images.githubusercontent.com/53712186/65944431-f23b1700-e431-11e9-9aa6-6ade92670895.PNG)

2019-10-01 08:05 UTC, oliverochman requested changes
This story is about presenting all of the products, but you have not done that yet.

2019-10-01 08:05 UTC, oliverochman commented on app/controllers/landing_controller.rb
> +class LandingController < ApplicationController
this should be a products controller

2019-10-01 08:05 UTC, oliverochman commented on app/views/landing/index.html.haml
> +%p Lasagna
u are hard coding these products

2019-10-01 08:05 UTC, oliverochman commented on features/product_list.feature
> +    When I'm on the landing page
Please change this to:
`Given I'm on the landing page`

2019-10-01 08:05 UTC, oliverochman commented on features/product_list.feature
> +    Then I should see "Lasagna"
Please indent this file properly

2019-10-01 08:06 UTC, shsteindorsson approved these changes
Approved

2019-10-01 11:18 UTC, shsteindorsson approved these changes

2019-10-01 11:30 UTC, AlexSaxena reviewed
AS

2019-10-01 11:32 UTC, beccaburns approved these changes

2019-10-01 11:32 UTC, lucamarial approved these changes

2019-10-01 11:32 UTC, miyeaier approved these changes

2019-10-01 11:32 UTC, ghost approved these changes

2019-10-01 11:33 UTC, miyeaier approved these changes

2019-10-01 11:33 UTC, miyeaier approved these changes

2019-10-01 11:34 UTC, miyeaier approved these changes

2019-10-01 11:35 UTC, lucamarial approved these changes

2019-10-01 11:50 UTC, lucamarial approved these changes

2019-10-01 11:51 UTC, lucamarial approved these changes

2019-10-01 11:52 UTC, beccaburns approved these changes

2019-10-01 11:52 UTC, miyeaier approved these changes

2019-10-01 11:52 UTC, shsteindorsson approved these changes

2019-10-01 11:53 UTC, lucamarial approved these changes

2019-10-01 11:54 UTC, ghost approved these changes

2019-10-01 13:31 UTC, miyeaier approved these changes

2019-10-01 13:32 UTC, lucamarial approved these changes

2019-10-01 13:35 UTC, beccaburns approved these changes

2019-10-01 13:37 UTC, ghost approved these changes

2019-10-01 13:38 UTC, shsteindorsson approved these changes

2019-10-01 13:40 UTC, faraznaeem requested changes
Good job, needs some changes until it is ready for a merge

2019-10-01 13:40 UTC, faraznaeem commented on app/models/product.rb
> +  validates :price, presence: :true
Refactor the validations

2019-10-01 13:40 UTC, faraznaeem commented on config/routes.rb
> +
Please remove extra lines

2019-10-01 13:40 UTC, faraznaeem commented on features/product_list.feature
> +    And I should see "300"
please group the products in order for example:
 
```
And I should see "apple pie"
And I should see "It is tasty"
And I should see "200"
And I should see "salad"
And I should see "It is green"
```
etc

2019-10-01 13:40 UTC, faraznaeem commented on features/step_definitions/basic_steps.rb
> +end
Move the assertion to a separate step definition file perhaps called assertions?

2019-10-01 13:54 UTC, lucamarial approved these changes

2019-10-01 13:55 UTC, ghost approved these changes

2019-10-01 13:56 UTC, miyeaier approved these changes

2019-10-01 13:56 UTC, ghost approved these changes

2019-10-01 14:05 UTC, miyeaier approved these changes

2019-10-01 14:06 UTC, miyeaier approved these changes

2019-10-01 14:16 UTC, lucamarial approved these changes

2019-10-01 14:41 UTC, beccaburns approved these changes

2019-10-01 14:42 UTC, shsteindorsson approved these changes

2019-10-01 14:50 UTC, ghost approved these changes

2019-10-02 07:41 UTC, lucamarial approved these changes

2019-10-02 07:41 UTC, shsteindorsson approved these changes

2019-10-02 07:47 UTC, oliverochman requested changes

2019-10-02 07:47 UTC, oliverochman commented on config/routes.rb
> +  resources :products
you need to limit what routes you have for products to what you actually use atm in the app

e.g.
`resources :products, only: [:index]`

2019-10-02 07:47 UTC, oliverochman commented on features/step_definitions/assertion_steps.rb
> +Given("the following product exist") do |table|
this is not an assertion

2019-10-02 07:47 UTC, oliverochman commented on features/step_definitions/basic_steps.rb
> +Then("I should see {string}") do |content|
this is an assertion

2019-10-02 08:24 UTC, oliverochman approved these changes

2019-10-02 08:24 UTC, merged